<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{
    const TYPE = array(
        'NULL' => 0,
        'XBXZCF' => 1,
        'XBXZXK'=> 2,
        'JGJCDXZJL' => 3,
        'JXSZLJDW' => 4,
        'SJJXMXX' => 5,
        'GGXYZHPJ' => 6,
        'YXQNZYZ' => 7,
        'XSPJXX' => 8,
        'SXBZXJGXX' => 9,
        'SXBZXRMD' => 10,
        'YSCRJZJJJZGRDXX' => 11,
        'JDCWFXX' => 12,
        'ZFCGDLJGXX' => 13,
        'SJQYJSZXRDXX' => 14,
        'JSZGXX' => 15,
        'SJYXXS' => 16,
        'JYJGXINXI' => 17,
        'GRRYXXJYJ' => 18,
        'JGRYXXSJYJ' => 19,
        'SFJDJGCYRYZGXX' => 20,
        'SFJDJGDJXX' => 21,
        'GZJGJBXX' => 22,
        'GZYXX' => 23,
        'JCFLFWSXX' => 24,
        'JCFLFWGZZJBXX' => 25,
        'LSSWSXX' => 26,
        'LSZYZGZXX' => 27,
        'JGRYXXSSFJ' => 28,
        'ZYJNZSXX' => 29,
        'YLBXXX' => 30,
        'YZTQSBXXHMD' => 31,
        'SYBXXX' => 32,
        'SBQYXX' => 33,
        'GZRYXX' => 34,
        'YZTQNMGGZHMD' => 35,
        'ZLJCQYXX' => 36,
        'SLGCZBXX' => 37,
        'QYYH' => 38,
        'QFGRYHXX' => 39,
        'QFQYYHXX' => 40,
        'DLYHSXHMDJG' => 41,
        'DLYHSXHMDZRR' => 42,
        'SLYSXKZXX' => 43,
        'GRRYXXJTJ' => 44,
        'ESCJDPGJGHZZS' => 45,
        'SHZZNJXX' => 46,
        'GRRYXXMZJ' => 47,
        'MBFQYML' => 48,
        'SHTTDJXX' => 49,
        'GJJLTQYRZXX' => 50,
        'YXZZDWJBGXX' => 51,
        'GRRYXXGDJ' => 52,
        'JGRYXXSWGXJ' => 53,
        'HSZYZGZXX' => 54,
        'YSZYZCHBGZC' => 55,
        'YSZYZGZXX' => 56,
        'WSHJHSYWYHJCXX' => 57,
        'YLHJSFWJGXX' => 58,
        'JBYFKZJGXX' => 59,
        'FYCRYJLXX' => 60,
        'WSZYJSZGKSWJXX' => 61,
        'QSWCXXXJDWBZ' => 62,
        'QYGSZXXX' => 63,
        'AJNSRXX' => 64,
        'ZDSSWFAJXX' => 65,
        'QYDSXZCFXX' => 66,
        'DTJXJGRXX' => 67,
        'TJDCDXML' => 68,
        'QIYEJBXX' => 69,
        'GTGSHXX' => 70,
        'CMQYSBXX' => 71,
        'YPLSQYXX' => 72,
        'JGRYXX' => 73,
        'SXQYHMD' => 74,
        'SPYPTSJBJLGR' => 75,
        'SPYPTSJBJLDW' => 76,
        'JXMPCPXX' => 77,
        'QYYCMLXX' => 78,
        'QYZXXX' => 79,
        'QYDXXX' => 80,
        'CCJCJGXX' => 81,
        'LSTDFWBA' => 82,
        'XZXKQYXX' => 83,
        'SYDWFRDJXX' => 84,
        'DZDAGZZDWGRBZJL' => 85,
        'TEST' => 500
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK'],
        ),
        IUserGroup::ID['XFGW'] => array(self::TYPE['JGJCDXZJL'], self::TYPE['TEST'], self::TYPE['SJJXMXX'], self::TYPE['GGXYZHPJ']),
        IUserGroup::ID['TXW'] => array(self::TYPE['YXQNZYZ']),
        IUserGroup::ID['XRMFY'] => array(self::TYPE['XSPJXX'], self::TYPE['SXBZXJGXX'], self::TYPE['SXBZXRMD']),
        IUserGroup::ID['XGAFJ'] => array(self::TYPE['YSCRJZJJJZGRDXX'], self::TYPE['JDCWFXX']),
        IUserGroup::ID['XCZJ'] => array(self::TYPE['ZFCGDLJGXX']),
        IUserGroup::ID['XGXJ'] => array(self::TYPE['SJQYJSZXRDXX']),
        IUserGroup::ID['XJYJ'] => array(
            self::TYPE['JSZGXX'],
            self::TYPE['SJYXXS'],
            self::TYPE['JYJGXINXI'],
            self::TYPE['GRRYXXJYJ'],
            self::TYPE['JGRYXXSJYJ']
        ),
        IUserGroup::ID['XSFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['SFJDJGDJXX'],
            self::TYPE['GZJGJBXX'],
            self::TYPE['GZYXX'],
            self::TYPE['JCFLFWSXX'],
            self::TYPE['JCFLFWGZZJBXX'],
            self::TYPE['LSSWSXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JGRYXXSSFJ']
        ),
        IUserGroup::ID['XRSJ'] => array(
            self::TYPE['ZYJNZSXX'],
            self::TYPE['YLBXXX'],
            self::TYPE['YZTQSBXXHMD'],
            self::TYPE['SYBXXX'],
            self::TYPE['SBQYXX'],
            self::TYPE['GZRYXX'],
            self::TYPE['YZTQNMGGZHMD']
        ),
        IUserGroup::ID['XZJJ'] => array(self::TYPE['ZLJCQYXX']),
        IUserGroup::ID['XSLJ'] => array(self::TYPE['SLGCZBXX']),
        IUserGroup::ID['XGDFGS'] => array(
            self::TYPE['QYYH'],
            self::TYPE['QFGRYHXX'],
            self::TYPE['QFQYYHXX'],
            self::TYPE['DLYHSXHMDJG'],
            self::TYPE['DLYHSXHMDZRR'],
        ),
        IUserGroup::ID['XJTYSJ'] => array(self::TYPE['SLYSXKZXX'], self::TYPE['GRRYXXJTJ']),
        IUserGroup::ID['XSWJ'] => array(self::TYPE['ESCJDPGJGHZZS']),
        IUserGroup::ID['XMZJ'] => array(
            self::TYPE['SHZZNJXX'],
            self::TYPE['GRRYXXMZJ'],
            self::TYPE['MBFQYML'],
            self::TYPE['SHTTDJXX']
        ),
        IUserGroup::ID['XNYNCJ'] => array(self::TYPE['GJJLTQYRZXX']),
        IUserGroup::ID['XWGXLJ'] => array(
            self::TYPE['YXZZDWJBGXX'],
            self::TYPE['GRRYXXGDJ'],
            self::TYPE['JGRYXXSWGXJ']
        ),
        IUserGroup::ID['XWJW'] => array(
            self::TYPE['HSZYZGZXX'],
            self::TYPE['YSZYZCHBGZC'],
            self::TYPE['YSZYZGZXX'],
            self::TYPE['WSHJHSYWYHJCXX'],
            self::TYPE['YLHJSFWJGXX'],
            self::TYPE['JBYFKZJGXX'],
            self::TYPE['FYCRYJLXX'],
            self::TYPE['WSZYJSZGKSWJXX'],
            self::TYPE['QSWCXXXJDWBZ']
        ),
        IUserGroup::ID['XSHUIWJ'] => array(self::TYPE['QYGSZXXX'], self::TYPE['AJNSRXX'], self::TYPE['ZDSSWFAJXX'], self::TYPE['QYDSXZCFXX']),
        IUserGroup::ID['XTJJ'] => array(self::TYPE['DTJXJGRXX'], self::TYPE['TJDCDXML']),
        IUserGroup::ID['XSCJDGLJ'] => array(
            self::TYPE['QIYEJBXX'],
            self::TYPE['GTGSHXX'],
            self::TYPE['CMQYSBXX'],
            self::TYPE['YPLSQYXX'],
            self::TYPE['JGRYXX'],
            self::TYPE['SXQYHMD'],
            self::TYPE['SPYPTSJBJLGR'],
            self::TYPE['SPYPTSJBJLDW'],
            self::TYPE['JXMPCPXX'],
            self::TYPE['QYYCMLXX'],
            self::TYPE['QYZXXX'],
            self::TYPE['QYDXXX'],
            self::TYPE['CCJCJGXX']
        ),
        IUserGroup::ID['XZWJ'] => array(self::TYPE['LSTDFWBA']),
        IUserGroup::ID['XCSGLJ'] => array(self::TYPE['XZXKQYXX']),
        IUserGroup::ID['XBWB'] => array(self::TYPE['SYDWFRDJXX']),
        IUserGroup::ID['XDAJ'] => array(self::TYPE['DZDAGZZDWGRBZJL']),
        IUserGroup::ID['XKJJ'] => array(self::TYPE['JXSZLJDW']),
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}
