<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['XFGW'] => 'XFGW',
        IUserGroup::ID['XWXCB'] => 'XWXCB',
        IUserGroup::ID['SLXWZZB'] => 'SLXWZZB',
        IUserGroup::ID['XWZFW'] => 'XWZFW',
        IUserGroup::ID['XRMFY'] => 'XRMFY',
        IUserGroup::ID['XJCY'] => 'XJCY',
        IUserGroup::ID['XGAFJ'] => 'XGAFJ',
        IUserGroup::ID['XCZJ'] => 'XCZJ',
        IUserGroup::ID['XGXJ'] => 'XGXJ',
        IUserGroup::ID['XJYJ'] => 'XJYJ',
        IUserGroup::ID['XSFJ'] => 'XSFJ',
        IUserGroup::ID['XRSJ'] => 'XRSJ',
        IUserGroup::ID['XZJJ'] => 'XZJJ',
        IUserGroup::ID['XGSL'] => 'XGSL',
        IUserGroup::ID['XGBDST'] => 'XGBDST',
        IUserGroup::ID['XSLJ'] => 'XSLJ',
        IUserGroup::ID['XJTYSJ'] => 'XJTYSJ',
        IUserGroup::ID['XSTHJJ'] => 'XSTHJJ',
        IUserGroup::ID['XSWJ'] => 'XSWJ',
        IUserGroup::ID['XMZJ'] => 'XMZJ',
        IUserGroup::ID['XNYNCJ'] => 'XNYNCJ',
        IUserGroup::ID['XWGXLJ'] => 'XWGXLJ',
        IUserGroup::ID['XWJW'] => 'XWJW',
        IUserGroup::ID['XSHUIWJ'] => 'XSHUIWJ',
        IUserGroup::ID['XTJJ'] => 'XTJJ',
        IUserGroup::ID['XSCJDGLJ'] => 'XSCJDGLJ',
        IUserGroup::ID['XYJGLJ'] => 'XYJGLJ',
        IUserGroup::ID['XZFJRB'] => 'XZFJRB',
        IUserGroup::ID['XZWJ'] => 'XZWJ',
        IUserGroup::ID['XXXZX'] => 'XXXZX',
        IUserGroup::ID['XBWB'] => 'XBWB',
        IUserGroup::ID['XKJJ'] => 'XKJJ',
        IUserGroup::ID['XSJJ'] => 'XSJJ',
        IUserGroup::ID['XCSGLJ'] => 'XCSGLJ',
        IUserGroup::ID['XDAJ'] => 'XDAJ',
        IUserGroup::ID['XZGH'] => 'XZGH',
        IUserGroup::ID['TXW'] => 'TXW',
        IUserGroup::ID['ZGRSSLZGS'] => 'ZGRSSLZGS',
        IUserGroup::ID['XGDFGS'] => 'XGDFGS',
        IUserGroup::ID['RBCXSLZGS'] => 'RBCXSLZGS',
        IUserGroup::ID['TMZ'] => 'TMZ',
        IUserGroup::ID['JSZ'] => 'JSZ',
        IUserGroup::ID['SLZ'] => 'SLZ',
        IUserGroup::ID['JGSX'] => 'JGSX',
        IUserGroup::ID['YX'] => 'YX',
        IUserGroup::ID['CPX'] => 'CPX',
        IUserGroup::ID['FTZ'] => 'FTZ',
        IUserGroup::ID['CSZ'] => 'CSZ',
        IUserGroup::ID['PGZ'] => 'PGZ',
        IUserGroup::ID['DYX'] => 'DYX',
    );
}
