<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        "XFGW" => 1,
        "XWXCB" => 2,
        "SLXWZZB" => 3,
        "XWZFW" => 4,
        "XRMFY" => 5,
        "XJCY" => 6,
        "XGAFJ" => 7,
        "XCZJ" => 8,
        "XGXJ" => 9,
        "XJYJ" => 10,
        "XSFJ" => 11,
        "XRSJ" => 12,
        "XZJJ" => 13,
        "XGSL" => 14,
        "XGBDST" => 15,
        "XSLJ" => 16,
        "XJTYSJ" => 17,
        "XSTHJJ" => 18,
        "XSWJ" => 19,
        "XMZJ" => 20,
        "XNYNCJ" => 21,
        "XWGXLJ" => 22,
        "XWJW" => 23,
        "XSHUIWJ" => 24,
        "XTJJ" => 25,
        "XSCJDGLJ" => 26,
        "XYJGLJ" => 27,
        "XZFJRB" => 28,
        "XZWJ" => 29,
        "XXXZX" => 30,
        "XBWB" => 31,
        "XKJJ" => 32,
        "XSJJ" => 33,
        "XCSGLJ" => 34,
        "XDAJ" => 35,
        "XZGH" => 36,
        "TXW" => 37,
        "ZGRSSLZGS" => 38,
        "XGDFGS" => 39,
        "RBCXSLZGS" => 40,
        "TMZ" => 41,
        "JSZ" => 42,
        "SLZ" => 43,
        "JGSX" => 44,
        "YX" => 45,
        "CPX" => 46,
        "FTZ" => 47,
        "CSZ" => 48,
        "PGZ" => 49,
        "DYX" => 50,
    );
}
